### ISSUE TITLE
Beckhoff PLC support

### ISSUE THREAD

**Issue by ElreboCM** [woopsa-protocol/Woopsa#16]
On l[ibraries.io ](https://libraries.io/nuget/Woopsa.NET)an early woopsa release an implementation for Beckhoff PLC was mentioned.
Has this implementation been dropped?

**Comment by francoisbirling** [comment]
Building on the experience gained during the development of a preliminary version, Woopsa has been redesigned from scratch since april 2015. The new version of the protocol is fully based on a simple object model, including for extended protocol functionalities like publish-subscribe or multi-requests.

Even if it broke compatibility with the very early release, we decided to adopt this new specification because it has gained in functionality, clarity, and simplicity. Implementations are already available in C#, C, JavaScript. 

The new version is thought to be implemented on many different platforms. Beckhoff PLCs, with their open ADS interface, are a perfect match to implement Woopsa. A new Woopsa gateway for Beckhof PLC is under developement and should be published within a few weeks.

As an open source project, we also welcome contributors who propose implementations on other platforms.

**Comment by francoisbirling** [comment]
A Woopsa-Ads bridge has been published (in the source code, not yet in the release)
