### ISSUE TITLE
Reference missing since update

### ISSUE THREAD

**Issue by JestarTE** [woopsa-protocol/Woopsa#22]
Hi,

I updated, with nuGet, from ver like 1.1.9 to 1.1.11 and some references are now missing. Please let me know me the new ones.
- new **WoopsaDynamicObject**(_client.Root);
- WoopsaClientProperty property = [...]
                      property.**Change** += subscription.Value;
- WoopsaServer woopsaServer = new WoopsaServer(InfoConnection, PORTSORTER);
              woopsaServer.**ClearCache();**

Thank you.

**Comment by francoisbirling** [comment]
Hi,

Some changes occured in Woopsa which caused small API compatibility breaks.

1) Dynamic has been partially redesigned. You should create a combined client+dynamic object in one step using the following syntax :

dynamic dynamicClient = new WoopsaDynamicClient("http://localhost/woopsa")

2) "Change" event has been removed, because several new needs appeared. It has been replaced by 2 "Subscribe" methods, to which you simply provide the delegate to call for each notification :

// Basic API with default values
public WoopsaClientSubscription Subscribe(EventHandler<WoopsaNotificationEventArgs> handler)
// Richer API that let specify monitoring and publish interval
public WoopsaClientSubscription Subscribe(EventHandler<WoopsaNotificationEventArgs> handler, TimeSpan monitorInterval, TimeSpan publishInterval);

These methods return a WoopsaClientSubscription that can be used to Unsubscribe later, by calling Unsubscribe() or Dispose() on it.

WoopsaClientProperty property = [...]
WoopsaClientSubscription subscription = property.Subscribe((sender, e) => { });
...
subscription.Dispose(); // or Subscription.Unsubscribe()

3) There is no more ClearCache method, because Woopsa performances have been optimized and the impact of the caching mechanism was neglectable. Accordingly, as it caused some pain for users in the management of the hierarchy updates, it has been entirely removed. There is no more caching for the path in Woopsa, and changes in the object hierarchy are reflected instantly. You don't have to care about that anymore.

Hope this helps.

Regards
